name: architecture_ptc
description: "Architecture PTC Flutter."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.5.0-203.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  ### used
  flutter_screenutil: ^5.7.0
  go_router: ^12.0.1
  intl:
  google_fonts: ^4.0.4
  file_picker: ^5.3.1
  image_picker: ^1.0.4
  percent_indicator:

  ## State Management
  flutter_bloc:
  bloc:


  ### used later
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.10+1
  animate_do:
  ## network
  dio:
  url_launcher:
  ## local
  get_storage:
  ## extinction
  shimmer:
  awesome_dialog:
  extended_image:
  flutter_styled_toast:
  infinite_scroll_pagination: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  ## tools
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0
  freezed:
  freezed_annotation:
  ## extinction
  faker:


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"

flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/information/
    - assets/lottie/
